version: '3'

services:
  server:
    build: ./images/apache
    environment:
      - APACHE_RUN_USER=#1000
    ports:
      - "8080:80"
      - "443:443"
    links:
      - db
    restart: 'always'
    volumes:
      - ./www/${PROJECT_NAME}:/var/www/html/
      - ${PHP_INI_HOST}:/usr/local/etc/php/php.ini
      - ${SITE_CONFIG_HOST}:/etc/apache2/sites-enabled
      - ${APACHE_LOG}:/var/log/apache2
    working_dir: /var/www

  db:
    build: ./images/mysql
    restart: always
    volumes:
      - ${MYSQL_PATH_HOST}:/var/lib/mysql
      - ${MYSQL_LOG}:/var/log/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}

  db-admin:
    build: ./images/phpmyadmin
    restart: always
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - '6080:80'

  composer:
    image: composer
    volumes:
      - ./www/${PROJECT_NAME}:/var/www/html/
    working_dir: /var/www/html/
    command: composer install